SMCi.WebUI/Areas/Admin/Controllers/ProfileController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using SMCi.WebCore.Extensions;
using SMCi.WebCore.Modules.Profile.Models;
using SMCi.WebCore.Modules.Profile.Services;
using SMCi.WebUI.Controllers.Base;
using Core.Web.Mvc.Alerts;
using Core.Web.Mvc.Filters;

namespace SMCi.WebUI.Areas.Admin.Controllers
{
    public class ProfileController : AuthorizedController
    {
        private readonly IProfileService _service;

        public ProfileController(IProfileService service)
        {
            _service = service;
        }

        public async Task<ActionResult> PersonalInfo()
        {
            return View(await _service.GetPersonalInfo());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> PersonalInfo(PersonalInfoModel model)
        {
            var result = await _service.UpdatePersonalInfo(model);

            if (result.Succeeded)
            {
                return View(model).WithSuccess("Update successfully");
            }

            ModelState.AddIdentityResultErrors(result);
            return View(model);
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> ChangePassword(ChangePasswordModel model)
        {
            var result = await _service.ChangePassword(model);

            if (result.Succeeded)
            {
                return RedirectToAction("ChangePassword").WithSuccess("Update successfully");
            }

            ModelState.AddIdentityResultErrors(result);
            return View(model);
        }

    }
}

SMCi.WebUI/Controllers/HomeController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SMCi.DataAccess.Entities;
using SMCi.WebCore.Modules.Home.Services;
using SMCi.WebCore.Modules.Posts.Models;
using SMCi.WebCore.Modules.Posts.Services;
using SMCi.WebUI.Controllers.Base;

namespace SMCi.WebUI.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IHomeService _service;

        public HomeController(IHomeService service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            return View("Company");
        }

        // Company's functions
        public ActionResult Company()
        {
            return View();
        }

        public ActionResult CompanyDetail(int id)
        {
            return View(_service.GetCompany(id));
        }

        [HttpPost]
        public ActionResult GetDistricts()
        {
            return Json(_service.GetDistricts());
        }

        [HttpPost]
        public ActionResult GetTowns(int districtId)
        {
            return Json(_service.GetTowns(districtId));
        }

        [HttpPost]
        public async Task<ActionResult> SearchCompany(string search, int districtId, int townId, int pageIndex = 0)
        {
            return PartialView("_CompanyItem", await _service.SearchCompany(search, districtId, townId, pageIndex));
        }

        //Van ban phap quy's functions
        public ActionResult Document()
        {
            return View();
        }

        public ActionResult DocumentViewer(string fileName)
        {
            return PartialView("_DocViewer", fileName);
        }

        [HttpPost]
        public async Task<ActionResult> SearchDocuments(string search, int catId, int pageIndex = 0)
        {
            return PartialView("_DocumentItem", await _service.SearchDocuments(search, catId, pageIndex));
        }

        public ActionResult GetFileView(string fileName)
        {
            var filePath = fileName;
            Response.AddHeader("Content-Disposition", "inline; filename=" + fileName);

            return File(filePath, MimeMapping.GetMimeMapping(fileName));
        }

        // Thong Tin Phan Anh's function
        public ActionResult Feedback()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<ActionResult> SearchFeedback(string search, int pageIndex = 0)
        {
            return PartialView("_FeedbackItem", await _service.SearchFeedback(search,  pageIndex));
        }

        [HttpPost]
        public async Task<ActionResult> SendFeedback(ThongTinTiepNhan model)
        {
            try
            {
                return Json(await _service.SaveFeedback(model));
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

SMCi.WebUI/Views/Home/Company.cshtml
@using SMCi.WebUI.Infrastructure.Extensions
<nav class="navbar navbar-static-top" role="navigation" style="margin-top: 20px;padding: 15px">
    <label class="smc-search-label" for="status">Tìm kiếm doanh nghiệp</label>
    <div class="row">
        <div class="col-sm-4">
            <div class="input-group m-b"><span class="input-group-addon"><i class="fa fa-search"></i></span> <input type="text" placeholder="Từ khóa tìm kiếm..." class="form-control" id="search-input"></div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                <select name="status" id="ajax-district-content" class="form-control">
                    <option value="-1" selected="">Huyện/Thị</option>
                </select>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group" id="ajax-town-content">
                <select name="status" id="select-town-option" class="form-control">
                    <option value="-1" selected="">Phường/Xã</option>
                </select>
            </div>
        </div>
        <div class="col-sm-2">
            <button class="btn btn-success ladda-button" onclick="companyCtrl.search();" id="search-button"><i class="fa fa-search"></i>&nbsp;&nbsp;<span class="bold">Tìm kiếm</span></button>
        </div>
    </div>
</nav>

<div class="row">
    <div class="col-md-9">
        <div id="ajax-company-content"></div>
        <div id="loading-content">
            @Html.Spinner()
        </div>
    </div>

    <div class="col-md-3">
        <ul id="sidebar-nav" class="list-group sidebar-nav-v1">
            <!-- Typography -->
            <li class="list-group-item active">
                <a>Huyện/Thị</a>
                <ul class="collapse in" id="menu-district-content">
                    @Html.Spinner()
                </ul>
            </li>
        </ul>
    </div>
</div>

@section scripts{
    @ViewHelper.RenderPageScript("home/company")
}

SMCi.WebUI/Views/Home/CompanyDetail.cshtml
@using SMCi.WebCore.Extensions
@model SMCi.DataAccess.Entities.Company

@{
    var logo = string.IsNullOrEmpty(Model.CompanyLogo) ? "/Content/img/portfolios/600x600/6.jpg" : Model.CompanyLogo;
}
<div class="container content mrg-top-30">
    <div class="row">
        <div class="col-lg-8 col-md-7">
            <div class="alert alert-warning fade in">
                <h1>@Model.CompanyName1</h1>
                <h2>@Model.CompanyName2</h2>
                <p>
                    @Model.CompanyName1 có địa chỉ tại @Model.CompanyAddr. Mã số thuế <strong>@Model.TaxCode</strong>
                    @*<p>Ngành nghề kinh doanh chính: <strong>Dịch vụ hỗ trợ giáo dục</strong></p>*@
            </div>
        </div>
        <div class="col-lg-4 col-md-5">
            <img src="@logo" class="img-responsive" />
        </div>
    </div>

    <div class="row mrg-top-30">
        <div class="col-lg-9 col-md-8">
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">

                    </div>
                </div>
            </div>

            <table class="table table-striped table-bordered table-responsive table-details">
                <tbody>
                    <tr>
                        <th>Mã số doanh nghiệp</th>
                        <td><h3><strong>@Model.CompanyCode</strong></h3></td>
                        <th>Ngày cấp</th>
                        <td>@Model.RegisterDate.ToDateTimeString()</td>
                        <th>Mã số thuế</th>
                        <td>@Model.TaxCode</td>
                    </tr>

                    <tr>
                        <th>Tên chính thức</th>
                        <td><h3>@Model.CompanyName1</h3></td>
                        <th>Tên khác</th>
                        <td colspan="3"><h3>@Model.CompanyName2</h3></td>
                    </tr>

                    <tr>
                        <th>Nơi đăng ký </th>
                        <td>@Model.RegisterPlace</td>
                        <th>Điện thoại</th>
                        <td colspan="3"> @Model.CompanyTel</td>
                    </tr>
                    <tr>
                        <th>Fax </th>
                        <td>@Model.CompanyFax</td>
                        <th>Email</th>
                        <td colspan="3"> @Model.CompanyMail</td>
                    </tr>

                    <tr>
                        <th>Địa chỉ trang web chính thức</th>
                        <td colspan="5"><h3>@Model.CompanyWebsite</h3></td>
                    </tr>
                    <tr>
                        <th>Địa chỉ trụ sở</th>
                        <td colspan="5"><h3>@Model.CompanyAddr</h3></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

SMCi.WebUI/Views/Home/Document.cshtml
@using SMCi.WebUI.Infrastructure.Extensions
<nav class="navbar navbar-static-top" role="navigation" style="margin-top: 20px;padding: 15px">
    <label class="smc-search-label" for="status">Tìm kiếm văn bản</label>
    <div class="row">
        <div class="col-sm-10">
            <div class="input-group m-b"><span class="input-group-addon"><i class="fa fa-search"></i></span> <input id="search-input" type="text" placeholder="Từ khóa tìm kiếm..." class="form-control"></div>
        </div>
        <div class="col-sm-2">
            <button class="btn btn-success ladda-button" onclick="documentCtrl.search()" id="search-button"><i class="fa fa-search"></i>&nbsp;&nbsp;<span class="bold">Tìm kiếm</span></button>
        </div>
    </div>
    <div class="ibox float-e-margins" style="padding-top: 10px; margin-bottom: 0">
        <div class="ibox-title" style="background-color: #1A7BB9">
            <h5 style="color: white">Lọc kết quả</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-down"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content" style="display: none">
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Loại văn bản</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Danh mục</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Người ký</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Cơ quan ban hành</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Ngày ban hành</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Ngày hiệu lực</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Tình trạng</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="row">
    <div class="col-md-9">
        <div id="ajax-document-content"></div>
        <div id="loading-content">
            @Html.Spinner()
        </div>
    </div>
    <div class="col-md-3">
        <ul id="danhmuc-nav" class="list-group sidebar-nav-v1">
            <li class="list-group-item active">
                <a>Danh mục</a>
                <ul class="collapse in" id="ajax-category-content">
                    <li>
                        <span class="badge badge-u">12234</span>
                        <a href="/tinh-thanh-pho/an-giang">Công văn</a>
                    </li>
                    <li>
                        <span class="badge badge-u">2337</span>
                        <a href="/tinh-thanh-pho/bac-can">Hiến pháp</a>
                    </li>
                    <li>
                        <span class="badge badge-u">10541</span>
                        <a href="/tinh-thanh-pho/bac-giang">Sắc lệnh</a>
                    </li>
                    <li>
                        <span class="badge badge-u">5158</span>
                        <a href="/tinh-thanh-pho/bac-lieu">Luật</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>


@section scripts{
    @ViewHelper.RenderPageScript("home/document")
}

SMCi.WebUI/Views/Home/Feedback.cshtml
@using Core.Web.Kendo
@using SMCi.WebCore.Modules.Posts.Models
@using SMCi.WebUI.Infrastructure.Extensions

<nav class="navbar navbar-static-top" role="navigation" style="margin-top: 20px;padding: 15px">
    <label class="smc-search-label" for="status">Tìm kiếm thông tin tiếp nhận</label>
    <div class="row">
        <div class="col-sm-10">
            <div class="input-group m-b"><span class="input-group-addon"><i class="fa fa-search"></i></span> <input id="search-input" type="text" placeholder="Từ khóa tìm kiếm..." class="form-control"></div>
        </div>
        <div class="col-sm-2">
            <button class="btn btn-success ladda-button" onclick="feedbackCtrl.search()" id="search-button"><i class="fa fa-search"></i>&nbsp;&nbsp;<span class="bold">Tìm kiếm</span></button>
        </div>
    </div>
</nav>

<a href="#infoform" class="btn btn-white pull-right" type="button"><i class="fa fa-envelope"></i>&nbsp;&nbsp;<span class="bold">Gửi thông tin</span></a>

<div class="ibox-content" style="padding: 0; padding-top: 10px; border: 0; max-height: 400px; overflow-y: scroll;" id="feedback-content">
    <table class="table table-striped table-bordered table-responsive table-details">
        <tbody id="ajax-feedback-content"></tbody>
    </table>

    <div id="loading-content">
        @Html.Spinner()
    </div>
</div>

<div class="ibox float-e-margins mrg-top-20" style="border: 1px #F3F3F4 solid" id="infoform">
    <div class="ibox-title">
        <h5>THÔNG TIN TIẾP NHẬN</h5>
    </div>
    <div class="ibox-content pdd-btm-10">
        <form id="form" class="form-horizontal row pdd-horizon-20">
            <p>Nếu bạn muốn thông tin với chúng tôi về doanh nghiệp, các hoạt động của cơ quan xin vui lòng điền đầy đủ thông tin bên dưới</p>
            <div class="col-md-6">
                <div class="form-group" style="margin-right: 0">
                    <label>Họ tên</label>
                    <div class="input-group m-b">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span><input id="form-hoten" type="text" placeholder="Họ tên..." class="form-control" required>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Email</label>
                    <div class="input-group m-b">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span><input id="form-email" type="email" placeholder="Email..." class="form-control" required>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label>Tiêu đề</label>
                    <div class="input-group m-b">
                        <span class="input-group-addon"><i class="fa fa-font"></i></span><input id="form-tieude" type="text" placeholder="Tiêu đề..." class="form-control" required>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group"><label>Nội dung</label> <textarea id="form-noidung" placeholder="Nội dung..." class="form-control" rows="5" required></textarea></div>
            </div>
            <button class="btn btn-sm btn-success pull-right m-t-n-xs ladda-button" type="submit"><strong>Gửi thông tin</strong></button>
        </form>
    </div>
</div>

<div id="modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="pop-title"></h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal row pdd-horizon-20">
                    <div class="col-md-12">
                        <div class="form-group" style="margin-right: 0">
                            <label>Tiêu đề</label>
                            <div class="input-group m-b">
                                <p id="pop-tieude"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Nội dung</label>
                            <div class="input-group m-b">
                                <p id="pop-noidung"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Trả lời</label>
                            <div class="input-group m-b">
                                <p id="pop-traloi"></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @ViewHelper.RenderPageScript("home/feedback")
}

SMCi.WebUI/Views/Home/Index.cshtml
@using SMCi.WebUI.Infrastructure.Extensions
@{
    ViewBag.Title = "Home";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            @{
                if (Request.IsAuthenticated)
                {
                    <div class="dropdown profile-element row">

                        <div class="col-md-1" style="width: 4% !important;padding-bottom: 5px">
                            @{
                                var avatarClass = "";
                                if (!string.IsNullOrEmpty(CurrentUser.Info.Avatar))
                                {
                                    avatarClass = "image-profile";
                                }

                                <span class="group-avatar @avatarClass" style="margin-top: -15px">
                                    <a class="btn btn-primary btn-circle letter-avatar" href="@Url.Action("PersonalInfo", "Profile", new {area = "Customer"})">
                                        <span>@CurrentUser.Info.UserName[0].ToString().ToUpper()</span>
                                    </a>
                                    <a class="btn btn-circle full-height image-avatar" href="@Url.Action("PersonalInfo", "Profile", new {area = "Customer"})">
                                        <img alt="avatar" class="img-circle img-md" src="@CurrentUser.Info.Avatar" />
                                    </a>
                                </span>
                            }
                        </div>

                        <div class="col-md-11">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="text-muted text-xs block" style="color: white">@(string.Join(" ", CurrentUser.Roles)) <b class="caret"></b></span>
                                </span>
                            </a>

                            <ul class="dropdown-menu m-t-xs">
                                <li><a href="@Url.Action("PersonalInfo", "Profile", new {area = "Admin"})">Manage Content</a></li>
                                <li><a href="@Url.Action("Logout", "Account", new {area = ""})">Log out</a></li>
                            </ul>
                        </div>
                    </div>

                }
                else
                {
                    <a class="btn btn-primary" href="@Url.Action("Login", "Account")">
                        <i class="fa fa-sign-in"></i> LOGIN
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Register", "Account")">
                        <i class="fa fa-user-plus"></i> SIGN UP
                    </a>
                }
            }

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>BLOG</h5>
                </div>
                <div class="wrapper wrapper-content animated fadeInRight" id="ajax-post-content" style="padding-left: 0; padding-right: 0">
                    @Html.Spinner()
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @ViewHelper.RenderPageScript("home/home")
}

SMCi.WebUI/Views/Home/_CompanyItem.cshtml
@using Core.Web.Router
@using SMCi.WebCore.Extensions
@model List<SMCi.WebCore.Modules.Home.Models.CompanyModel>

@foreach (var item in Model)
{
    var logo = string.IsNullOrEmpty(item.CompanyLogo) ? "/Content/img/portfolios/600x600/6.jpg" : item.CompanyLogo;
    <div class="row">
    <div class="col-md-3">
        <img src="@logo" class="img-responsive" />
    </div>
    <div class="col-md-9">
        <h2 class="no-mrg-top">
            <a href="@Url.Action("CompanyDetail","Home", new { id = item.CompanyID.ToFriendly(item.CompanyName1) })" title="@item.CompanyName1">@item.CompanyName1</a>
        </h2>
        <div class="row">
            <div class="col-md-12">
                <h3>
                    Mã số thuế: <strong><a href="@Url.Action("CompanyDetail","Home", new { id = item.CompanyID.ToFriendly(item.CompanyName1) })" title="Mã số thuế: @item.TaxCode">@item.TaxCode</a></strong>
                </h3>
            </div>
            <div class="col-md-4">
                <p>
                    Huyện/Thị: <a href="/tinh-thanh-pho/ha-noi"><strong>@item.RegisterPlace</strong></a>
                </p>
            </div>
            <div class="col-md-4">
                <p>Ngày thành lập: @item.RegisterDate.ToDateTimeString()</p>
            </div>
            <div class="col-md-12">
                <p>
                    Địa chỉ: <strong>@item.CompanyAddr</strong>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    Điện thoại: <strong>@item.CompanyTel</strong>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    Email: <strong>@item.CompanyMail</strong>
                </p>
            </div>
        </div>
        @*<ul class="list-inline posted-info">
            <li>Ngành nghề hoạt động: <a href="/nganh-nghe/ban-buon-thuc-pham"><strong>Bán buôn thực phẩm</strong></a></li>
        </ul>*@
    </div>
    <div class="col-md-12">
        <hr>
    </div>
    </div>
}

SMCi.WebUI/Views/Home/_DocViewer.cshtml
@model string

<iframe style="width: 100%; height: 100%" src="https://docs.google.com/gview?url=@Model&embedded=true"></iframe>

SMCi.WebUI/Views/Home/_DocumentItem.cshtml
@model List<SMCi.DataAccess.Entities.VanBanPhapQuy>

@foreach (var item in Model)
{
    <div class="row">
        <div class="col-md-3">
            <img src="/Content/img/portfolios/600x600/6.jpg" class="img-responsive" />
        </div>
        <div class="col-md-9 row">
            <div class="col-md-8">
                <h2 class="no-mrg-top">
                    @item.TieuDe
                </h2>
                <p>
                    @item.NoiDung
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    Ngày ban hành: @item.CreatedDate.ToString("dd/MM/yyyy")
                </p>
                @*<p>
                        Ngày hiệu lực:
                    </p>*@
                <p>Tình trạng: <a href=""><strong>Còn hiệu lực</strong></a></p>
            </div>
            <div class="col-md-12">
                <hr style="margin-top: 10px !important;margin-bottom: 10px!important" />
                <div class="row">
                    <div class="col-md-2">
                        <a target="_blank" href="@Url.Action("DocumentViewer", "Home", new { fileName = item.DocUrl})" tar class="btn btn-outline btn-link"><i class="fa fa-eye"></i> Xem</a>
                    </div>
                    <div class="col-md-2">
                        <a href="@Url.Action("GetFileView", "Home", new { fileName = "~/Upload/Test.docx"})" class="btn btn-outline btn-link"><i class="fa fa-download"></i> Tải xuống</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <hr />
        </div>
    </div>
}

SMCi.WebUI/Views/Home/_FeedbackItem.cshtml
@using SMCi.DataAccess.Entities
@model List<ThongTinTiepNhan>

@foreach (var item in Model)
{
    <tr>
        <td>@item.Id</td>
        <td>@item.TieuDe</td>
        <td>@item.NoiDung</td>
        <td><a onclick="feedbackCtrl.viewAnswer('Mã tiếp nhận @item.Id','@item.TieuDe', '@item.NoiDung', '@item.TraLoi')" class="popup-inline" data-toggle="modal" data-target="#modal">Xem trả lời</a></td>
    </tr>
}