SMCi.WebUI/Areas/Admin/Controllers/ManageVanBanPhapQuyController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.Web.Mvc.Alerts;
using Core.Web.Mvc.Filters;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SMCi.WebCore.Modules.VanBanPhapQuys.Models;
using SMCi.WebCore.Modules.VanBanPhapQuys.Services;
using SMCi.WebUI.Controllers.Base;

namespace SMCi.WebUI.Areas.Admin.Controllers
{
    public class ManageVanBanPhapQuyController : HostAuthorizedController
    {
        private readonly IVanBanPhapQuyService _service;

        public ManageVanBanPhapQuyController(IVanBanPhapQuyService service)
        {
            _service = service;
        }

        public ActionResult Grid_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_service.GetAll().ToDataSourceResult(request));
        }

        public Task<ActionResult> Grid_Destroy([DataSourceRequest] DataSourceRequest request, VanBanPhapQuyModel model)
        {
            return ExecuteGridActionAsync(request, model, () => _service.Delete(model.Id));
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new VanBanPhapQuyModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Create(VanBanPhapQuyModel model)
        {
            try
            {
                await _service.Create(model);
                return RedirectToAction("Index").WithSuccess("Tạo thành công");
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            return View(await _service.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Edit(VanBanPhapQuyModel model)
        {
            try
            {
                await _service.Update(model);
                return View(model).WithSuccess("Cập nhật thành công");
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }
            return View(model);
        }
    }
}

SMCi.WebUI/Areas/Admin/Views/ManageVanBanPhapQuy/Create.cshtml
@using Core.Web.Extensions
@model SMCi.WebCore.Modules.VanBanPhapQuys.Models.VanBanPhapQuyModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Thông tin Văn bản</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.FormPost())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ErrorSummary()

                        @Html.EditorForModel("Form")

                        <button type="submit" class="ladda-button btn btn-primary">
                            <i class="fa fa-save"></i> Tạo
                        </button>

                        <a class="btn btn-default" href="@Url.Action("Index", "ManageVanBanPhapQuy", new { area = "Admin" })">
                            <i class="fa fa-arrow-left"></i> Trở lại
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        Validator.default();
    </script>
}

SMCi.WebUI/Areas/Admin/Views/ManageVanBanPhapQuy/Edit.cshtml
@using Core.Web.Extensions
@model SMCi.WebCore.Modules.VanBanPhapQuys.Models.VanBanPhapQuyModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Thông tin Văn bản</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.FormPost())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ErrorSummary()

                        @Html.EditorForModel("Form")

                        <button type="submit" class="ladda-button btn btn-primary">
                            <i class="fa fa-save"></i> Cập nhật
                        </button>

                        <a class="btn btn-default" href="@Url.Action("Index", "ManageVanBanPhapQuy", new { area = "Admin" })">
                            <i class="fa fa-arrow-left"></i> Trở lại
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        Validator.default();
    </script>
}

SMCi.WebUI/Areas/Admin/Views/ManageVanBanPhapQuy/Index.cshtml
@using Core.Web.Kendo
@using Kendo.Mvc.UI
@using SMCi.WebCore.Modules.VanBanPhapQuys.Models

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Danh sách Văn bản</h5>
                    <div class="ibox-tools">
                        <div class="buttons">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Create", "ManageVanBanPhapQuy")">
                                <i class="fa fa-plus"></i> Thêm mới
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    @(Html.Kendo().Grid<VanBanPhapQuyModel>()
                                        .DefaultSettings()
                                        .Columns(columns =>
                                        {
                                            columns.Bound(p => p.TieuDe).ClientTemplate("<a href='/Admin/ManageVanBanPhapQuy/Edit/#:Id#'>#:TieuDe#</a>");
                                            columns.Bound(p => p.NoiDung);
                                            columns.Bound(p => p.iStatus);
                                            columns.BoundBoolean(p => p.IsPublish);
                                            columns.Command(x =>
                                            {
                                                x.Destroy().Text("Xóa");
                                            }).Width(50);
                                        })
                                          .DataSource(dataSource => dataSource
                                              .Ajax()
                                              .DefaultSettings()
                                              .Model(model =>
                                              {
                                                  model.Id(p => p.Id);
                                              })
                                              .Read(read => read.Action("Grid_Read", "ManageVanBanPhapQuy"))
                                              .Destroy(destroy => destroy.Action("Grid_Destroy", "ManageVanBanPhapQuy"))
                                          ).Deferred()
                    )
                </div>
            </div>
        </div>
    </div>
</div>